### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by wensens** [wensens/LearningGithubClient#2]
for every one to know the project

**Comment by wensens** [comment]
@wensniu

**Comment by wensens** [comment]
@wensniu do you have any suggestion?

**Comment by wensniu** [comment]
>do you have any suggestion?
first thing is to learning document of mastering markdown.

**Comment by wensens** [comment]
> do you have any suggestion?
> first thing is to learning document of mastering markdown.

ok. the website is https://guides.github.com/
also there are video guides.

**Comment by wensens** [comment]
> do you have any suggestion?
> first thing is to learning document of mastering markdown.
> ok. the website is https://guides.github.com/
> also there are video guides.

https://github.com/wensens/LearningGithubClient/issues/2
